<?php
/**
 * 
 * 
 * 
 */

namespace REALYTICLAB_THEME\Includes;

use REALYTICLAB_THEME\Includes\Traits\Singleton;

class Assets {
    use Singleton;

    protected function __construct() {
        // load classes here!
        $this -> setup_hooks();
    }

    protected function setup_hooks() {
        add_action("wp_enqueue_scripts", [$this, "register_scripts"]);
        add_action("wp_enqueue_scripts", [$this, "register_styles"]);
        add_action("wp_enqueue_scripts", [$this, "react_build_scripts"]);
    }

    public function register_styles() {

    }

    public function register_scripts() {
        
    }

    public function react_build_scripts() {
        $theme_dir = get_template_directory();
        $theme_uri = get_template_directory_uri();

        $js_files = glob($theme_dir . '/dist/assets/*.js');
        $css_files = glob($theme_dir . '/dist/assets/*.css');

        if (!empty($js_files)) {
            // Ambil file terbaru berdasarkan waktu
            $latest_js = array_reduce($js_files, function($a, $b) {
                return filemtime($a) > filemtime($b) ? $a : $b;
            });

            wp_enqueue_script(
                'react-app',
                $theme_uri . '/dist/assets/' . basename($latest_js),
                [],
                null,
                true
            );
        }

        if (!empty($css_files)) {
            $latest_css = array_reduce($css_files, function($a, $b) {
                return filemtime($a) > filemtime($b) ? $a : $b;
            });

            wp_enqueue_style(
                'react-style',
                $theme_uri . '/dist/assets/' . basename($latest_css),
                [],
                null
            );
        }
    }


    // public function react_build_scripts() {
    //     // Get the theme directory path and URI
    //     $theme_dir = get_template_directory();
    //     $theme_uri = get_template_directory_uri();
        
    //     // Path to the asset manifest file generated by the React build
    //     $manifest_path = $theme_dir . '/build/asset-manifest.json';

    //     // Check if the manifest file exists
    //     if ( file_exists( $manifest_path ) ) {
    //         // Read and decode the JSON manifest file
    //         $manifest = json_decode( file_get_contents( $manifest_path ), true );

    //         // Check if the main JavaScript and CSS files are in the manifest
    //         if ( isset( $manifest['files']['main.js'] ) && isset( $manifest['files']['main.css'] ) ) {
    //             $main_js_file = $manifest['files']['main.js'];
    //             $main_css_file = $manifest['files']['main.css'];

    //             // Enqueue your React app's main JavaScript bundle using the dynamic filename
    //             wp_enqueue_script(
    //                 'my-react-app-bundle',
    //                 $theme_uri . '/build' . $main_js_file,
    //                 array( 'wp-element' ), // Use 'wp-element' as a dependency for React apps
    //                 null,
    //                 true
    //             );

    //             // Enqueue your React app's main CSS bundle using the dynamic filename
    //             wp_enqueue_style(
    //                 'my-react-app-styles',
    //                 $theme_uri . '/build' . $main_css_file,
    //                 array(),
    //                 null
    //             );
    //         }
    //     }
    // }
}